### ISSUE TITLE
Exception `AttributeError: __exit__` when *not* passing `None` in consoleLock

### ISSUE THREAD

**Issue by TheRealOne78** [brmmm3/fastlogging#14]
Hi. I noticed that if I pass True/False for the consoleLock kwarg I get an `AttributeError: __exit__` exception.

Here's some code worth reproducing.

```py
#!/usr/bin/env python3

from fastlogging import LogInit

logger1 = LogInit(console=True, colors=True, consoleLock=None) # This is fine

logger1.debug("Hello")
logger1.info("Hello")
logger1.warning("Hello")
logger1.error("Hello")
logger1.fatal("Hello")
logger1.exception("Hello")

logger2 = LogInit(console=True, colors=True, consoleLock=True) # This is nolonger fine
#logger2 = LogInit(console=True, colors=True, consoleLock=False) # Same result as the line from above

logger2.debug("Hello") # Exception __exit__
logger2.info("Hello")
logger2.warning("Hello")
logger2.error("Hello")
logger2.fatal("Hello")
logger2.exception("Hello")
```

And here's the backtrace:
```sh
❯ ./py.py
24.07.25 00:48:37: root: DEBUG  : Hello
24.07.25 00:48:37: root: INFO   : Hello
24.07.25 00:48:37: root: WARNING: Hello
24.07.25 00:48:37: root: ERROR  : Hello
24.07.25 00:48:37: root: FATAL  : Hello
5024.07.25 00:48:37: root: EXCEPT : Hello
NoneType: None

Traceback (most recent call last):
  File "/home/therealone/git/RenaultAPI/tmp/./py.py", line 17, in <module>
    logger2.debug("Hello")
  File "fastlogging/fastlogging.pyx", line 249, in fastlogging.fastlogging.Logger.debug
  File "fastlogging/fastlogging.pyx", line 239, in fastlogging.fastlogging.Logger.__log
  File "fastlogging/fastlogging.pyx", line 426, in fastlogging.fastlogging.Logger._logMessage
AttributeError: __exit__
```

**Comment by brmmm3** [comment]
You need to provide a Lock object, not True.

```python
from threading import Lock
lock = Lock()

logger2 = LogInit(console=True, colors=True, consoleLock=lock)
...
```

**Comment by TheRealOne78** [comment]
Oh alright, it makes sense now
